# Generated by Django 4.0.1 on 2022-03-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='dateofbirth',
            field=models.IntegerField(max_length=30),
        ),
    ]
