# Generated by Django 4.0.1 on 2022-03-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_alter_parent_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='dateofbirth',
            field=models.IntegerField(max_length=50),
        ),
    ]
