# Generated by Django 4.0.1 on 2022-03-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_child_alter_parent_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='dateofbirth',
            field=models.DateTimeField(max_length=50),
        ),
    ]
