# Generated by Django 4.0.1 on 2022-03-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_remove_parent_contact2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='contact1',
            field=models.IntegerField(),
        ),
    ]
