# Generated by Django 4.0.1 on 2022-03-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0008_alter_child_dateofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='regno',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='child',
            name='dateofbirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='parent',
            name='contact1',
            field=models.IntegerField(default=0),
        ),
    ]
