# Generated by Django 4.0.1 on 2022-03-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0009_child_regno_alter_child_dateofbirth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='orgname',
            field=models.CharField(default='mother therisa org', max_length=50),
        ),
    ]
