# Generated by Django 4.0.1 on 2022-03-25 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0010_child_orgname'),
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.child')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.parent')),
            ],
        ),
    ]
