# Generated by Django 4.0 on 2022-06-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0011_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='child_maintenance_amount',
            field=models.IntegerField(default=0),
        ),
    ]
